The replica master 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/trainer/cnn_copy_sobel.py", line 292, in <module> train_model(**arguments) File "/root/.local/lib/python2.7/site-packages/trainer/cnn_copy_sobel.py", line 241, in train_model validation_steps = 300) File "/root/.local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper return func(*args, **kwargs) File "/root/.local/lib/python2.7/site-packages/keras/models.py", line 1223, in fit_generator initial_epoch=initial_epoch) File "/root/.local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper return func(*args, **kwargs) File "/root/.local/lib/python2.7/site-packages/keras/engine/training.py", line 2083, in fit_generator generator_output = next(output_generator) File "/root/.local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 553, in get raise StopIteration(e) StopIteration: min() arg is an empty sequence To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=917750264014&resource=ml_job%2Fjob_id%2Fcnncopysobel_train_20171119_121052&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22cnncopysobel_train_20171119_121052%22

